import type { jsPDF as JsPDF } from 'jspdf';
import { exceptionText, project, projectFiles, studyAssumptions } from '../data';
import type { AuditEvent, Evidence, ReviewRecord } from '../types';
import { canExportDraft } from './safety';

const WATERMARK = 'DRAFT FOR ENGINEERING REVIEW — NOT APPROVED FOR ISSUE';

const addDraftFrame = (doc: JsPDF, page: number) => {
  const width = doc.internal.pageSize.getWidth();
  const height = doc.internal.pageSize.getHeight();

  doc.setDrawColor(221, 151, 37);
  doc.setLineWidth(0.6);
  doc.line(16, 14, width - 16, 14);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(173, 107, 17);
  doc.text(WATERMARK, 16, 10.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(99, 105, 110);
  doc.text(`CV104-AF-2026 · Rev C · Page ${page}`, width - 16, height - 10, { align: 'right' });
  doc.text('Generated by ArcFlash Copilot · Engineer judgment remains required', 16, height - 10);
};

const sectionTitle = (doc: JsPDF, title: string, y: number) => {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(173, 107, 17);
  doc.text(title.toUpperCase(), 16, y);
  doc.setDrawColor(218, 218, 212);
  doc.line(16, y + 2, 194, y + 2);
};

const body = (doc: JsPDF, text: string | string[], x: number, y: number, width = 178) => {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.2);
  doc.setTextColor(35, 39, 42);
  const lines = Array.isArray(text) ? text : doc.splitTextToSize(text, width);
  doc.text(lines, x, y);
  return y + lines.length * 4.6;
};

const drawEvidenceSnapshot = (doc: JsPDF, item: Evidence, y: number) => {
  doc.setFillColor(23, 29, 33);
  doc.roundedRect(16, y, 178, 49, 1.5, 1.5, 'F');
  doc.setDrawColor(49, 60, 66);
  for (let x = 22; x < 188; x += 12) doc.line(x, y + 7, x, y + 43);
  for (let gy = y + 7; gy < y + 44; gy += 9) doc.line(22, gy, 188, gy);

  doc.setFont('courier', 'bold');
  doc.setTextColor(244, 166, 35);
  doc.setFontSize(10);
  doc.text(item.id, 23, y + 12);
  doc.setFont('courier', 'normal');
  doc.setTextColor(225, 230, 232);
  doc.setFontSize(7.8);
  doc.text(`${project.id} · ${project.shortCase} · IEEE 1584-2018`, 23, y + 18);
  doc.text(`Incident energy        ${item.incidentEnergy?.toFixed(1)} cal/cm²`, 23, y + 27);
  doc.text(`Arc-flash boundary     ${item.boundary?.toFixed(0)} in`, 23, y + 33);
  doc.text(`Clearing time          ${item.clearingTime == null ? 'NOT AVAILABLE' : `${item.clearingTime.toFixed(3)} s`}`, 23, y + 39);

  if (item.status === 'needs_review' || item.status === 'deferred') {
    doc.setFillColor(244, 166, 35);
    doc.rect(151, y + 8, 35, 7, 'F');
    doc.setTextColor(26, 27, 27);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6.5);
    doc.text('REVIEW REQUIRED', 168.5, y + 12.8, { align: 'center' });
  }
};

export const reportFilename = `${project.id}_${project.revision.replace(' ', '-')}_arc-flash_DRAFT-review.pdf`;

export async function generateDraftPdf(evidence: Evidence[], review: ReviewRecord | null, audit: AuditEvent[]) {
  if (!review || !canExportDraft(evidence, review)) {
    throw new Error('Complete evidence disposition and engineer acknowledgement are required before draft export.');
  }

  const { default: JsPdfConstructor } = await import('jspdf');
  const doc = new JsPdfConstructor({ unit: 'mm', format: 'a4', compress: true });
  let page = 1;
  addDraftFrame(doc, page);

  doc.setFillColor(11, 15, 17);
  doc.rect(0, 14, 210, 102, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(244, 166, 35);
  doc.setFontSize(9);
  doc.text('ARCFLASH / COPILOT', 16, 31);
  doc.setTextColor(242, 244, 245);
  doc.setFontSize(25);
  doc.text('Arc-flash study', 16, 53);
  doc.text('evidence package', 16, 64);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(170, 181, 187);
  doc.text(project.name, 16, 78);
  doc.text(`${project.number} · ${project.revision} · ${project.shortCase}`, 16, 86);
  doc.setDrawColor(244, 166, 35);
  doc.roundedRect(16, 96, 92, 10, 1.5, 1.5, 'S');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.2);
  doc.setTextColor(244, 166, 35);
  doc.text('DRAFT · INTERNAL ENGINEERING REVIEW ONLY', 62, 102.5, { align: 'center' });

  sectionTitle(doc, 'Review status', 132);
  let y = body(doc, `Reviewed for draft export by ${review.reviewer} (${review.role}) on ${review.timestamp}. This acknowledgement does not authorize issue, construction, labelling, or professional certification.`, 16, 143);
  y += 7;
  sectionTitle(doc, 'Executive summary', y);
  y = body(doc, `ArcFlash Copilot extracted ${evidence.length} equipment results from ${project.shortCase}. ${evidence.length - review.unresolvedCount} evidence items are accepted for draft assembly. ${review.unresolvedCount ? 'MCC-01 retains an unresolved protective-device clearing-time exception and requires engineering verification.' : 'All missing fields in this draft have an explicit engineer-supplied disposition.'}`, 16, y + 11);
  y += 8;
  sectionTitle(doc, 'Important limitation', y);
  body(doc, 'This package records computer-use evidence and assembles a draft. It does not replace the study calculation engine, select protective-device settings, exercise engineering judgment, or issue a stamped engineering report.', 16, y + 11);

  doc.addPage();
  page += 1;
  addDraftFrame(doc, page);
  sectionTitle(doc, '1 · Project information', 27);
  y = 38;
  const projectRows = [
    ['Project', project.name], ['Project number', project.number], ['Client', project.client],
    ['Revision', project.revision], ['Study case', project.studyCase], ['Method', 'IEEE 1584-2018'],
  ];
  projectRows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(92, 98, 101); doc.text(label, 16, y);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(35, 39, 42); doc.text(value, 58, y); y += 7;
  });
  y += 4;
  sectionTitle(doc, '2 · Source files', y);
  y += 11;
  projectFiles.forEach((file) => {
    doc.setFont('courier', 'normal'); doc.setFontSize(7.7); doc.setTextColor(35, 39, 42);
    doc.text(file.name, 16, y);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(file.status === 'warning' ? 173 : 90, file.status === 'warning' ? 107 : 100, file.status === 'warning' ? 17 : 101);
    doc.text(file.status === 'warning' ? 'Requires review' : 'Ready', 194, y, { align: 'right' }); y += 6;
  });
  y += 5;
  sectionTitle(doc, '3 · Study assumptions', y);
  y += 11;
  studyAssumptions.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(92, 98, 101); doc.text(label, 16, y);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(35, 39, 42); doc.text(value, 72, y); y += 6.5;
  });

  doc.addPage();
  page += 1;
  addDraftFrame(doc, page);
  sectionTitle(doc, '4 · Equipment and extracted results', 27);
  y = 38;
  const cols = [16, 42, 86, 113, 143, 170];
  const headers = ['Equipment', 'Description', 'Fault kA', 'Clearing s', 'IE cal/cm²', 'AFB in'];
  doc.setFillColor(232, 230, 224); doc.rect(16, y - 5, 178, 9, 'F');
  headers.forEach((header, index) => { doc.setFont('helvetica', 'bold'); doc.setFontSize(7); doc.setTextColor(54, 58, 61); doc.text(header, cols[index], y); });
  y += 10;
  evidence.forEach((item) => {
    const values = [item.id, item.description, item.boltedFault?.toFixed(1) ?? '—', item.clearingTime?.toFixed(3) ?? 'N/A', item.incidentEnergy?.toFixed(1) ?? '—', item.boundary?.toFixed(0) ?? '—'];
    values.forEach((value, index) => { doc.setFont(index === 0 ? 'courier' : 'helvetica', index === 0 ? 'bold' : 'normal'); doc.setFontSize(7.4); doc.setTextColor(item.clearingTime == null ? 153 : 35, item.clearingTime == null ? 92 : 39, item.clearingTime == null ? 18 : 42); doc.text(value, cols[index], y); });
    doc.setDrawColor(225, 224, 219); doc.line(16, y + 3, 194, y + 3); y += 10;
  });
  y += 5;
  sectionTitle(doc, '5 · Missing information and exceptions', y);
  const mcc = evidence.find((item) => item.id === 'MCC-01');
  y = body(doc, mcc?.clearingTime == null
    ? `EX-001 · MCC-01\n${exceptionText}\nDisposition: Deferred to engineer review; value remains Not available.`
    : `MCC-01 correction record\nProtective-device clearing time: ${mcc.clearingTime.toFixed(3)} s\nProvenance: Engineer-supplied content · ${mcc.engineerNote ?? 'No note provided.'}`,
  16, y + 11);
  y += 8;
  sectionTitle(doc, '6 · PPE recommendation field', y);
  body(doc, 'PPE arc-rating fields are reproduced from the source study for engineer review. ArcFlash Copilot does not select PPE, determine task-specific risk controls, or approve labels.', 16, y + 11);

  evidence.forEach((item, index) => {
    doc.addPage();
    page += 1;
    addDraftFrame(doc, page);
    sectionTitle(doc, `Evidence ${index + 1} · ${item.evidenceId}`, 27);
    drawEvidenceSnapshot(doc, item, 37);
    y = 96;
    const evidenceRows = [
      ['Equipment', `${item.id} · ${item.description}`], ['Source screen', item.sourceScreen],
      ['Screenshot', item.screenshot], ['Captured', item.capturedAt], ['Agent action', item.action],
      ['Confidence', `${Math.round(item.confidence * 100)}%`], ['Verification', item.status.replace('_', ' ')],
    ];
    evidenceRows.forEach(([label, value]) => {
      doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(92, 98, 101); doc.text(label, 16, y);
      doc.setFont('helvetica', 'normal'); doc.setTextColor(35, 39, 42); doc.text(doc.splitTextToSize(value, 132), 58, y); y += Math.max(7, doc.splitTextToSize(value, 132).length * 4.5);
    });
  });

  doc.addPage();
  page += 1;
  addDraftFrame(doc, page);
  sectionTitle(doc, 'Audit trail', 27);
  y = 38;
  audit.slice(-24).forEach((event) => {
    if (y > 274) { doc.addPage(); page += 1; addDraftFrame(doc, page); sectionTitle(doc, 'Audit trail · continued', 27); y = 38; }
    doc.setFont('courier', 'normal'); doc.setFontSize(7); doc.setTextColor(99, 105, 110); doc.text(event.timestamp, 16, y);
    doc.setFont('helvetica', 'bold'); doc.setTextColor(35, 39, 42); doc.text(event.actor, 37, y);
    doc.setFont('courier', 'bold'); doc.setTextColor(173, 107, 17); doc.text(event.type, 69, y);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(65, 69, 72); doc.text(doc.splitTextToSize(event.detail, 75), 119, y);
    y += Math.max(7, doc.splitTextToSize(event.detail, 75).length * 4.2);
  });
  y += 7;
  sectionTitle(doc, 'Engineer issue authorization', y);
  body(doc, 'Final issue authorization: ____________________________________\nProfessional seal / signature: ________________________________\nDate: ____________________     Revision: ____________________', 16, y + 12);

  doc.save(reportFilename);
  return reportFilename;
}

export { WATERMARK };
